
package kz.gamma.webra.services.client.jaxws;

import kz.gamma.webra.services.client.WebClientProps;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "WebraWS", targetNamespace = "http://www.gamma.kz/webra/xsd", wsdlLocation = "/Service.wsdl")
public class WebraWS_Service
    extends Service
{

    private final static URL WEBRAWS_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL(WebClientProps.getInstance().get(WebClientProps.WSDL_LOCATION));
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WEBRAWS_WSDL_LOCATION = url;
    }

    public WebraWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebraWS_Service() {
        super(WEBRAWS_WSDL_LOCATION, new QName("http://www.gamma.kz/webra/xsd", "WebraWS"));
    }

    /**
     * 
     * @return
     *     returns WebraWS
     */
    @WebEndpoint(name = "WebraWSPort")
    public WebraWS getWebraWSPort() {
        return super.getPort(new QName("http://www.gamma.kz/webra/xsd", "WebraWSPort"), WebraWS.class);
    }

}
