//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 02:22:29 PM ALMT 
//


package kz.gamma.webra.services.common.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for algTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="algTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GOST"/>
 *     &lt;enumeration value="RSA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "algTYPE")
@XmlEnum
public enum AlgTYPE {


    /**
     * Ошибка валидации по XSD. При наличии неправильно сформированных xml сообщений.
     * 
     */
    GOST,

    /**
     * Ошибка подписи. При ошибках криптографии и подписи.
     * 
     */
    RSA;

    public String value() {
        return name();
    }

    public static AlgTYPE fromValue(String v) {
        return valueOf(v);
    }

}
