//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 02:22:29 PM ALMT 
//


package kz.gamma.webra.services.common.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.gamma.kz/webra/xsd}PkiDocument">
 *       &lt;sequence>
 *         &lt;element name="order" type="{http://www.gamma.kz/webra/xsd}Order"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientId","fxOrderDetails"
})
@XmlRootElement(name = "docCreateOrderIn")
public class DocCreateOrderIn
    extends PkiDocument
{

    @XmlElement(required = true)
    protected BigInteger clientId;
    public BigInteger getClientId() {
        return clientId;
    }
    public void setClientId(BigInteger value) {
        this.clientId = value;
    }

    @XmlElement(required = true)
    protected List<OrderDetail> fxOrderDetails;
    public List<OrderDetail> getFxOrderDetails() {
        return fxOrderDetails;
    }
    public void setFxOrderDetails(List<OrderDetail> value) {
        this.fxOrderDetails = value;
    }

}
