//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 02:22:29 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gamma.kz/webra/xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kz.gamma.webra.services.common.entities;
