//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 02:22:29 PM ALMT 
//


package kz.gamma.webra.services.common.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Abstract Document
 * 
 * <p>Java class for PkiDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PkiDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="dateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PkiDocument")
@XmlSeeAlso({
    DocGetOrganizationOut.class,
    DocRequestCertIn.class,
    DocOrderListIn.class,
    DocUpdatePersonOut.class,
    DocCreatePersonOut.class,
    DocCityListIn.class,
    DocCountryListOut.class,
    DocUpdateCUserIn.class,
    DocRevokeCertIn.class,
    DocRemovePersonIn.class,
    DocChangePasswordOut.class,
    DocGetCertListOut.class,
    DocCreateOrderIn.class,
    DocCountryListIn.class,
    DocConfirmOrderOut.class,
    DocGetPersonListOut.class,
    DocTariffListOut.class,
    DocRequestListOut.class,
    DocFindPersonOut.class,
    DocUpdatePersonIn.class,
    DocRevokeCertOut.class,
    DocBankListOut.class,
    DocOrderListOut.class,
    DocGetPersonListIn.class,
    DocUpdateCUserOut.class,
    DocPositionListIn.class,
    DocSetDNIn.class,
    DocIssuerListIn.class,
    DocFindPersonIn.class,
    DocTariffListIn.class,
    DocRegionListOut.class,
    DocChangePasswordIn.class,
    DocPositionListOut.class,
    DocSetDNOut.class,
    DocRequestListIn.class,
    DocLoadPersonOut.class,
    DocGetCertListIn.class,
    DocGetRolesOut.class,
    DocGetTumarOut.class,
    DocRegionListIn.class,
    DocGetTumarIn.class,
    DocGetRolesIn.class,
    DocRequestCertOut.class,
    DocCityListOut.class,
    DocGetOrganizationIn.class,
    DocRemovePersonOut.class,
    DocConfirmOrderIn.class,
    DocBankListIn.class,
    DocLoadPersonIn.class,
    DocCreateOrderOut.class,
    DocIssuerListOut.class,
    DocCreatePersonIn.class,
    DocGenerateSANListIn.class,
    DocGenerateSANListOut.class
})
public class PkiDocument {

    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

}
