//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 02:22:29 PM ALMT 
//


package kz.gamma.webra.services.common.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="requestTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="registration"/>
 *     &lt;enumeration value="initialization"/>
 *     &lt;enumeration value="revocation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "requestTYPE")
@XmlEnum
public enum RequestTYPE {


    /**
     * Регистрация сертификата
     * 
     */
    @XmlEnumValue("registration")
    REGISTRATION("registration"),
    @XmlEnumValue("initialization")
    INITIALIZATION("initialization"),

    /**
     * Отзыв сертификата
     * 
     */
    @XmlEnumValue("revocation")
    REVOCATION("revocation");
    private final String value;

    RequestTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestTYPE fromValue(String v) {
        for (RequestTYPE c: RequestTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
