//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 02:22:29 PM ALMT 
//


package kz.gamma.webra.services.common.entities;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * RequestDetail
 * 
 * <p>Java class for RequestDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.gamma.kz/webra/xsd}uLong20TYPE" minOccurs="0"/>
 *         &lt;element name="tariffDetailId" type="{http://www.gamma.kz/webra/xsd}uLong20TYPE" minOccurs="0"/>
 *         &lt;element name="profile" type="{http://www.gamma.kz/webra/xsd}string255TYPE" minOccurs="0"/>
 *         &lt;element name="bodySigned" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="certBody" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestDetail", propOrder = {
    "id",
    "tariffDetailId",
    "profile",
    "bodySigned",
    "certBody"
})
public class RequestDetail {

    protected BigInteger id;
    protected BigInteger tariffDetailId;
    protected String profile;
    protected byte[] bodySigned;
    protected byte[] certBody;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the tariffDetailId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTariffDetailId() {
        return tariffDetailId;
    }

    /**
     * Sets the value of the tariffDetailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTariffDetailId(BigInteger value) {
        this.tariffDetailId = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfile(String value) {
        this.profile = value;
    }

    /**
     * Gets the value of the bodySigned property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getBodySigned() {
        return bodySigned;
    }

    /**
     * Sets the value of the bodySigned property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setBodySigned(byte[] value) {
        this.bodySigned = ((byte[]) value);
    }

    /**
     * Gets the value of the certBody property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCertBody() {
        return certBody;
    }

    /**
     * Sets the value of the certBody property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCertBody(byte[] value) {
        this.certBody = ((byte[]) value);
    }

}
