//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.02 at 02:22:29 PM ALMT 
//


package kz.gamma.webra.services.common.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for requestStatusTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="requestStatusTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="novel"/>
 *     &lt;enumeration value="approved1"/>
 *     &lt;enumeration value="approved2"/>
 *     &lt;enumeration value="rejected"/>
 *     &lt;enumeration value="processed"/>
 *     &lt;enumeration value="error"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "requestStatusTYPE")
@XmlEnum
public enum RequestStatusTYPE {


    /**
     * новый
     * 
     */
    @XmlEnumValue("novel")
    NOVEL("novel"),

    /**
     * Подтвержден менеджером
     * 
     */
    @XmlEnumValue("approved1")
    APPROVED_1("approved1"),

    /**
     * Подтвержден офицером безопасности
     * 
     */
    @XmlEnumValue("approved2")
    APPROVED_2("approved2"),

    /**
     * отменен
     * 
     */
    @XmlEnumValue("rejected")
    REJECTED("rejected"),

    /**
     * обработан
     * 
     */
    @XmlEnumValue("processed")
    PROCESSED("processed"),

    /**
     * содержит ошибки
     * 
     */
    @XmlEnumValue("error")
    ERROR("error");
    private final String value;

    RequestStatusTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestStatusTYPE fromValue(String v) {
        for (RequestStatusTYPE c: RequestStatusTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
